apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: golang-15724 
  janus-idp.io/tekton: golang-15724
  backstage.io/kubernetes-id: golang-15724
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: golang-15724
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  